### ISSUE TITLE
Unable to match `OneOf` with `slice`

### ISSUE THREAD

**Issue by thanhnguyen2187** [alexpantyukhin/go-pattern-match#40]
Hi!

Using `OneOf` with `slice` does not work:

```go
func TestMatch(t *testing.T) {
	isMatched, _ := Match([]string{"one", "two", "three"}).
		When(OneOf([]string{"one", "two", "three"}), true).
		Result()

	assert.True(t, isMatched)
}
```

Do you have any idea on what is the fix for this? My task involve matching a slice of string with some pattern groups, in which `Match` is a perfect match. For a workaround, I can try writing a wrapper like:

```go
func OneOfWrapper(items ...interface{}) boolean {
	isMatched, _ := ...
	return isMatched || OneOfWrapper(items[1:]...)
}
```

But it is not a preferable way, I suppose.

Thanks for the awesome library!

**Comment by alexpantyukhin** [comment]
Hello! Firstly I want to say thanks for using the lib and feedback! 

About the example in the comment. 
Please, see the test: https://github.com/alexpantyukhin/go-pattern-match/blob/master/match_test.go#L119

Your example would be correct if you make some changes. For example:
```go

func TestMatch(t *testing.T) {
	isMatched, _ := Match([]string{"one", "two", "three"}).
		When([]interface{}{"one", OneOf("one", "two", "three"), "three"}, true).
		Result()

	assert.True(t, isMatched)
}
```

**Comment by thanhnguyen2187** [comment]
Hi Alex. Thanks for the response. I do understand the case `OneOf("one", "two", "three")` that you said, but what I really meant was that I expected `OneOf` to work with multiple slices within it.

```go
func TestMatch(t *testing.T) {
	isMatched, _ := Match([]string{"one", "two", "three"}).
		When(OneOf([]string{"one", "two", "three"}, []string{"four", "five", "six"}), true).
		Result()

	assert.True(t, isMatched)
}
```

**Comment by alexpantyukhin** [comment]
Hi! Ah, I think I've gotten what you mean. You want to use multiple patterns, and even one of these works - return the one thing. Well for now this is not a feature in the current implementation, but it could be in the future.
Sure you can use the approach which you presented. I also could advise to try another way: Add `When`s in loop. Something like:

```go

pMatching := Match([]string{"one", "two", "three"})
for _, matchItem := range matchItems {
    pMatching = pMatching.When(matchItem, result)
}

isMatched, _ := pMatching.Result()
```
I really appreciate your point about improve the library interface! thank you much!
