### ISSUE TITLE
Syntax Error: Unexpected newline in match.go:183:85

### ISSUE THREAD

**Issue by rnice01** [alexpantyukhin/go-pattern-match#44]
Hey! Loving this library, I come from the Elixir/Elm world and wanted to give Go a try but missed my pattern matching.

Getting a strange error when trying to compile an example from the README.
```
$ belm go run belm.go
# github.com/alexpantyukhin/go-pattern-match
../../go/pkg/mod/github.com/alexpantyukhin/go-pattern-match@v0.0.0-20220912082227-fff88c15359c/match.go:183:85: syntax error: unexpected newline, expecting { after if clause
```

Go version
```
go version go1.19.1 darwin/amd64
```

The opening brace is there, just on a newline. I managed to fix it by moving the opening brace to the same line of the `if` statement. So not sure if this a problem with the version of Go I'm using? But it seems very odd there would be a change to the compiler that wouldn't allow a newline after an `if` statement.

**Comment by alexpantyukhin** [comment]
Hey @rnice01 !
Thank you a lot! Nice catch! 
I made some refactoring changes for the lib #45  . It should fix that.
