### ISSUE TITLE
Move to GitHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by Panquesito7** [alexpantyukhin/go-pattern-match#46]

**Comment by alexpantyukhin** [comment]
thank you @Panquesito7 ! Nice idea!

**Comment by Panquesito7** [comment]
I'll see if I can work on this in the next few days. Feel free to remind me in a week if I don't create any PR. Thanks. 🙂

**Comment by alexpantyukhin** [comment]
Cool! All contributions are welcome!
